name: AlphaClientServer.CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
        cache: true
        
    - name: Install dependencies
      run: |
          go mod download
    - name: Copy the Source File
      run: | 
          cp /src/* .

    - name: Build
      run: go build -o /main

    # - name: Test
    #   run: go test -v 
