name: AlphaClientServer.CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build_go:
    name: Build the Go App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Setup the Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
          cache: true

      - name: Install the Go dependencies
        run: |
          go mod download
      - name: Copy the Source Files
        run: |
          cp ./src/* .

      - name: Build the packages
        run: go build -v ./...

  build_tf:
    name: Build the Terraform Configuration Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Setup the Terraform Environment
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
          terraform_wrapper: false

      - name: Terraform Init and Validate
        run: |
          cd ./TF
          terraform init
          terraform validate

  build_docker:
    name: Build and Push the Docker Image
    needs: [build_go, build_tf]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alphaserver:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/alphaserver:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/alphaserver:buildcache,mode=max
  
  deploy_tf:
    name: Deploy the Kubernetes Cluster
    runs-on: ubuntu-latest
    needs: [build_docker]
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Install and Setup the Terraform Environment
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
          terraform_wrapper: false
      - 
        name: Terraform Plan and Apply
        run: 
          cd ./TF
          terraform init
          terraform plan
          terraform apply --auto-approve
